### ISSUE TITLE
I require tor but it's not installed. Run ./install.sh. Aborting.

### ISSUE THREAD

**Issue by MarshmallowSoup** [g0r60n/InstaShell#5]
How to install tor for instashell ?

**Comment by myfirstgithubaccHk** [comment]
apt install tor
And after installation is completed
Type tor

**Comment by 9harsha** [comment]
I require tor but it's not installed. Run ./install.sh. Aborting.
how can i solve this error

**Comment by qpwo130** [comment]
I require tor but it's not installed. Run ./install.sh. Aborting.
